/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.Random;

public class App {
    public String getGreeting() {
    }

    public static void main(String[] args) {
        String[][] tabuleiro = new String[10][10];
        for (int i = 0; i < 10; i++) {
            for (int b = 0; b < 10; b++) {
                tabuleiro[i][b] = ".";
            }  
        }

        int portaAvioes = 5;
        int encouracado = 4;

        Random random = new Random();

        while (true) {
            int posx = random.nextInt(10);
            System.out.println(posx);
            int posy = random.nextInt(10);
            System.out.println(posy);
            while (true) {
                if (posx + portaAvioes <= 10) {
                    //porta aviões
                    for (int i = 0; i < portaAvioes; i++) {
                        tabuleiro[posx+i][posy] = "P";          
                    }
                }
                break; 
            }

            
            
            posx = random.nextInt(10);
            System.out.println(posx);
            posy = random.nextInt(10);
            System.out.println(posy);

            while (true) {
                if (posy + encouracado <= 10) {
                    //ENcouraçado
                    for (int i = 0; i < encouracado; i++) {
                        tabuleiro[posx][posy+i] = "E";          
                    }
                }
                break; 
            }

            
            
            break;
        }

    
        for (int i = 0; i < 10; i++) {
            for (int b = 0; b < 10; b++) {
                System.out.print(tabuleiro[i][b] + " ");
            }  
            System.out.println();
        }
    }
}
